apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: gomovies-deployment 
spec: 
  selector: 
    matchLabels: 
      app: gomovies 
  replicas: 1 # tells deployment to run 1 pods matching the template 
  template:
    metadata: 
      labels: 
        app: gomovies 
    spec: 
      containers: 
      - name: gomovies 
        image: docker.io/heck909/gomovies:#{Build.BuildId}#
        ports: 
        - containerPort: 8080 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: gomovies-service 
spec: 
  selector: 
    app: gomovies 
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 8080
  type: LoadBalancer
